### ISSUE TITLE
评论人数过多无法拉去品论ID

### ISSUE THREAD

**Issue by qq290598268** [nasawz/lucky_bilibili_web#17]
如题，例如https://www.bilibili.com/video/BV1mY411L7k8?spm_id_from=333.999.0.0 链接无法拉去数据

**Comment by nasawz** [comment]
已经仔细的排查过了   

确认是如下：
1. 腾讯云的服务器不支持返回大于6M的数据
2. 客户端js不支持设置超时时间

除非换架构方案，不然无法解决这个问题。

**Comment by qq290598268** [comment]
> 已经仔细的排查过了
> 
> 确认是如下：
> 
> 1. 腾讯云的服务器不支持返回大于6M的数据
> 2. 客户端js不支持设置超时时间
> 
> 除非换架构方案，不然无法解决这个问题。



是否考虑 有自行云端部署或者本地部署方案呢？

**Comment by nasawz** [comment]
这个用的人很少    以后如果人多的话可以考虑

**Comment by qq290598268** [comment]
> 这个用的人很少 以后如果人多的话可以考虑

好的，感谢！
